create table if not exists saga_tcc_transaction (
  saga_id varchar(64) not null comment 'Saga 事务唯一标识',
  coordinator_app varchar(128) not null comment '协调方应用名称',
  business_code varchar(128) not null comment '协调方业务编码',
  business_id varchar(128) not null comment '业务唯一标识',
  status varchar(32) not null comment 'Saga 事务状态',
  branch_count int not null default 0 comment '分支总数',
  last_error varchar(2000) null comment '最近一次错误信息',
  next_retry_time datetime(3) not null comment '下次可重试时间',
  create_time datetime(3) not null comment '创建时间',
  update_time datetime(3) not null comment '更新时间',
  primary key (saga_id),
  key idx_saga_tcc_tx_status_retry (status, next_retry_time),
  key idx_saga_tcc_tx_business (coordinator_app, business_code, business_id)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_bin row_format=dynamic;

create table if not exists saga_tcc_branch (
  id bigint not null auto_increment comment '分支记录主键',
  saga_id varchar(64) not null comment '所属 Saga 事务唯一标识',
  branch_no int not null comment 'Saga 事务内的分支序号',
  target_app varchar(128) not null comment '目标参与方应用名称',
  bus_code varchar(128) not null comment '参与方业务编码',
  request_class varchar(512) not null comment '生产方请求 DTO 类名，仅用于诊断',
  request_json longtext not null comment '序列化后的请求 JSON',
  status varchar(32) not null comment '分支状态',
  try_attempts int not null default 0 comment 'Try 命令已派发次数',
  confirm_attempts int not null default 0 comment 'Confirm 命令已派发次数',
  cancel_attempts int not null default 0 comment 'Cancel 命令已派发次数',
  failure_attempt int not null default 0 comment '已记录失败结果的命令尝试序号',
  last_error varchar(2000) null comment '最近一次错误信息',
  next_retry_time datetime(3) not null comment '下次可重试时间',
  create_time datetime(3) not null comment '创建时间',
  update_time datetime(3) not null comment '更新时间',
  primary key (id),
  unique key uk_saga_tcc_branch_no (saga_id, branch_no),
  key idx_saga_tcc_branch_status_retry (status, next_retry_time, id),
  key idx_saga_tcc_branch_saga (saga_id)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_bin row_format=dynamic;

create table if not exists saga_tcc_outbox (
  id bigint not null auto_increment comment 'Outbox 记录主键',
  message_key varchar(160) not null comment '消息幂等键',
  saga_id varchar(64) not null comment '所属 Saga 事务唯一标识',
  branch_id bigint not null comment '所属分支记录主键',
  topic varchar(255) not null comment 'RocketMQ 消息主题',
  tag varchar(64) not null comment 'RocketMQ 消息标签',
  action varchar(32) not null comment '命令动作：TRY、CONFIRM 或 CANCEL',
  command_attempt int not null comment '当前命令派发序号',
  payload longtext not null comment '序列化后的消息 JSON 载荷',
  status varchar(32) not null comment 'Outbox 消息状态',
  attempts int not null default 0 comment '消息发送失败次数',
  claim_token varchar(64) null comment '发布任务抢占令牌',
  next_retry_time datetime(3) not null comment '下次可抢占或发送时间',
  create_time datetime(3) not null comment '创建时间',
  update_time datetime(3) not null comment '更新时间',
  primary key (id),
  unique key uk_saga_tcc_outbox_msg (message_key),
  key idx_saga_tcc_outbox_ready (status, next_retry_time, id),
  key idx_saga_tcc_outbox_claim_token (claim_token),
  key idx_saga_tcc_outbox_branch_attempt (branch_id, status, action, command_attempt, attempts),
  key idx_saga_tcc_outbox_saga (saga_id, branch_id)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_bin row_format=dynamic;

create table if not exists saga_tcc_participant_log (
  id bigint not null auto_increment comment '参与方幂等日志主键',
  local_app varchar(128) not null comment '当前参与方应用名称',
  coordinator_app varchar(128) not null comment '协调方应用名称',
  saga_id varchar(64) not null comment 'Saga 事务唯一标识',
  branch_id bigint not null comment '协调方分支记录主键',
  target_app varchar(128) not null comment '命令目标应用名称',
  bus_code varchar(128) not null comment '参与方业务编码',
  request_hash varchar(64) not null comment '请求 JSON 的 SHA-256 哈希值',
  try_status varchar(32) null comment 'Try 阶段执行状态',
  confirm_status varchar(32) null comment 'Confirm 阶段执行状态',
  cancel_status varchar(32) null comment 'Cancel 阶段执行状态',
  create_time datetime(3) not null comment '创建时间',
  update_time datetime(3) not null comment '更新时间',
  primary key (id),
  unique key uk_saga_tcc_participant_branch (local_app, coordinator_app, saga_id, branch_id),
  key idx_saga_tcc_participant_saga (saga_id, branch_id)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_bin row_format=dynamic;
